using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace CSC236_nBrassell_ContactMgrApp.Models
{
    public class Contact
    {
        //Primary key - generated by database
        [Key]
        public int ContactId { get; set; }

        [Required(ErrorMessage = "Please enter a first name.")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Please enter a last name.")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Please enter a phone number.")]
        public string Phone { get; set; }

        [Required(ErrorMessage = "Please enter an email address.")]
        public string Email { get; set; }

        public string Organization { get; set; } // No validation bc optional
        public DateTime DateAdded { get; set; } // Will be set by application

        //Foreign Key
        [ForeignKey("CategoryId")]
        public Category Category { get; set; }

        [Range(1, 100000000, ErrorMessage = "Please select a category")]
        public int CategoryId { get; set; }

        //Read-Only property
        public string Slug => FirstName?.Replace(" ", "_").ToLower()
            + "_" + LastName?.Replace(" ", "_").ToLower();
    }
}
